project:
  type: book
  output-dir: docs

book:
  title: "Recherche d'information dans les sources spécialisées en sciences & techniques"
  subtitle: "Service de référence et recherche dans les sources spécialisées (7V46-SRI)"
  author:
      - name: "Raphaël Grolimund"
        orcid: "0000-0002-8047-9888"
        affiliations:
          - name: "Haute école de gestion de Genève"
            department: "Infothèque"
  date: "2024-04-27"
  language: "fr"
  license: "CC BY 4.0"
  pdf-url: "https://github.com/grolimur/HEG-764-31"
  status : "living document"
  type: "book"
  version: "0.9"
  abstract: "Ce manuel est principalement conçu pour accompagner le séminaire PLU6058, qui vise à améliorer les compétences informationnelles des étudiant.es des cycles supérieurs de l'Université de Montréal. Cependant, il peut également être utilisé de manière autonome et autodidacte pour la recherche et l'utilisation de la documentation dans le cadre d'un projet de recherche. En outre, il peut être utilisé comme une ressource éducative par les enseignant.es en bibliothèque de recherche."
  
  chapters:
  - index.qmd
  - part: chapters/_bases-multidisciplinaires.qmd
    chapters:
    - chapters/Compendex.qmd
    - chapters/Inspec.qmd
    - chapters/ScienceDirect.qmd
    - chapters/Scopus.qmd
    - chapters/SpringerLink.qmd
    - chapters/WileyOnlineLibrary.qmd
    - chapters/WoS.qmd
  - part: chapters/_bases-specialisees.qmd
    chapters:
    - chapters/ACMDigitalLibrary.qmd
    - chapters/CAS-references.qmd
    - chapters/CINAHL.qmd
    - chapters/Embase.qmd
    - chapters/GEOBASE.qmd
    - chapters/GeoRef.qmd
    - chapters/IEEEXplore.qmd
    - chapters/MathSciNet.qmd
    - chapters/MEDLINE.qmd
    - chapters/zbMATH.qmd
  - part: chapters/_archives-ouvertes.qmd
    chapters:
    - chapters/archives-institutionnelles.qmd
    - chapters/archives-thematiques.qmd
  - part: chapters/_moteurs-de-recherche.qmd
    chapters:
    - chapters/BASE.qmd
    - chapters/CORE.qmd
    - chapters/google-scholar.qmd
    - chapters/LENS.qmd
  - part: chapters/_reseaux-sociaux.qmd
    chapters:
    - chapters/Academia.edu.qmd
    - chapters/ResearchGate.qmd
  - part: chapters/_plateformes.qmd
    chapters:
    - chapters/ACM.qmd
    - chapters/ieee.qmd
    - chapters/ovid.qmd
    - chapters/proquest.qmd
    - chapters/pubmed.qmd
    - chapters/sciencedirect-elsevier.qmd
    - chapters/scopus-elsevier.qmd
    - chapters/springer.qmd
    - chapters/webofscience.qmd
    - chapters/wiley.qmd
    - chapters/comparaison-plateformes.qmd
  - part: versions.qmd