## Historique des versions

| version | date | commentaire |
| :-- | ---------: | :--------------- |
| 0.1 | 17.05.2016 | version initiale |
| 0.2 | 16.05.2017 | mise à jour 2017 |
| 0.2.1 | 18.05.2017 | corr. ScienceDirect |
| 0.2.2 | 26.05.2017 | corr. coquilles |
| 0.2.4 | 24.09.2017 | ajout nouveauté arXiv + corr. lien |
| 0.2.9.1beta | 6.05.2018 | refactorisation du contenu |
| 0.2.9.2beta | 6.05.2018 | vérification de tous les liens du document |
| 0.2.9.3beta | 7.05.2018 | mise à jour des informations concernant les ressources |
| 0.2.9.4beta | 7.05.2018 | corrections mineures concernant les ressources |
| 0.2.9.5beta | 8.05.2018 | mise à jour des plateformes |
| 0.2.9.6beta | 11.05.2018 | mise en page infographies + versions.md |
| 0.3 | 14.05.2018 | dernière corr. sur v0.2.9 (CAplus + infographie) |
| 0.3.9 RC | 12.05.2019 | mise à jour bases de données et plateformes |
| 0.3.9 RC2 | 12.05.2019 | corr. erreur table des matières et màj couverture |
| 0.3.9 RC3 | 12.05.2019 | màj illustration de taille de bases de données |
| 0.4 | 13.05.2019 | màj ill. couverture temporelle des bases de données et infos sur les plateformes |
| 0.4.9 RC4 | 20.04.2020 | ajout ACM Digital Library (dans ressources & plateformes) |
| 0.4.9 RC5 | 30.04.2020 | màj des informations sur les ressources |
| 0.4.9 RC6 | 30.04.2020 | màj des informations sur les plateformes |
| 0.4.9 RC7 | 2.05.2020 | màj nom archive ouverte Uni NE |
| 0.4.9 RC8 | 2.05.2020 | correction CAplus |
| 0.5 | 9.05.2020 | màj des infographies |
| 0.5.1 | 10.05.2020 | comparatif plateformes complété + modif. lien dans README |
| 0.5.9 RC | 28.04.2021 | màj bases de données + plateformes & suppression données de recherche + tableau comparatif |
| 0.5.9 RC2 | 28.04.2021 | correction liens et noms de fichiers |
| 0.5.9 RC3 | 28.04.2021 | corrections dans le sommaire et la mise en page |
| 0.5.9 RC4 | 28.04.2021 | suppression des mentions "notes personnelles" + corrections coquilles |
| 0.6 | 17.05.2021 | publication de la version 2021 et dernières corr. mineures |
| 0.7 | 26.05.2022 | publication de la version 2022 |
| 0.8 | 21.05.2023 | publication de la version 2023 |
| 0.9 | 27.04.2024 | version 2024: migration vers Quarto + ajout de CORE et The Lens, suppression de Twitter |
