# ARCHIVES THÉMATIQUES

*Voici quelques* ***archives thématiques*** *pertinentes en Suisse romande*   

| archives ouvertes | domaine | nb docs/titres |
| :-- | :-- | --: |
| [arXiv](https://arxiv.org) | maths, physique, informatique | 2'400'000 publications |
| [bioRxiv](https://biorxiv.org/about-biorxiv) | sciences biomédicales | 232'000 publications |
| [CERN Document Server](https://cds.cern.ch/) | physique des hautes énergies | 537'000 publications |

`arXiv` collecte des ***preprints***, documents n'ayant pas encore été soumis ou validés dans une revue scientifique. Certaines publications, lorsque c'est autorisé, sont enrichies du ***postprint***, version revue, corrigée et validée, mais pas encore mise en forme par l'éditeur. Dans arXiv, la date correspond à la date de dépôt. arXiv a été créé en 1991. Il se peut toutefois que certains documents aient été rédigés avant cette date.   

**biorXiv** ne collecte plus aussi que des ***preprints***. Il y a toutefois le lien vers la plateforme de l'éditeur lorsque l'article a été validé. Le contenu de [medRxiv](https://www.medrxiv.org/), archive ouverte en médecine lancée en 2016, est inclus dans bioRxiv. L'inverse est vrai aussi. Dans bioRxiv, la date correspond à la date de dépôt sur la plateforme. Cette dernière a été créée en 2013. bioRxiv n'est pas indexé dans [BASE](BASE.qmd).   

Les recherches menées au CERN ne concerne qu'un domaine bien précis de la physique, la physique des hautes énergies. Par contre, comme le CERN fournit la très grande majorité des publications dans ce domaine, le **CERN Document Server** est une base de données importante.   


## Les serveurs de *preprints* fleurissent...

Depuis 2016, plusieurs *clones* d'arXiv ont fait leur apparition. Dans le domaines des sciences et techniques, notons [engrXiv](https://osf.io/preprints/engrxiv/), [ChemRxiv](https://chemrxiv.org/engage/chemrxiv/public-dashboard), [EarthArXiv](https://eartharxiv.org/) et [PaleorXiv](https://paleorxiv.org/), qui ont vocation à collecter les *preprints* en ingénierie, chimie, sciences de la terre et paléontologie respectivement. La plupart de ces serveurs utilisent la même plateforme, [OSF Preprints](https://osf.io/preprints/), ce qui les rend interopérables les unes avec les autres. Il est donc possible de rechercher sur toutes ces plateformes à la fois. Cela représente tout de même plus de **2.4 millions de preprints**...
